version: '2'
services:
  mongo:
    image: mongo
  nginx:
    image: nginx
    volumes:
      - ./ReduxOMDB/dist:/var/www/
      - ./default:/etc/nginx/conf.d/default.conf
    environment:
     - NGINX_PORT=80
    links:
      - "web:web"
    ports:
      - "80:80"
    stdin_open: true
    tty: true
  web:
    build: .
    command:  npm start
    volumes:
      - ./omdblogin/bin:/app/bin
      - ./omdblogin/routes:/app/routes
      - ./omdblogin/views:/app/views
      - ./omdblogin/public:/app/public
      - ./omdblogin/config:/app/config
    links:
      - "mongo:mongo"
    ports:
      - "3000:3000"